### ISSUE TITLE
Getting error from the "dummy_repo_data" property.

### ISSUE THREAD

**Issue by Duder-onomy** [ebrian/gitdummy#12]
Hi, Great repo BTW. Considering our Github accounts are our resume.

Given this `repos.json`
```json
[
    {
        "target_repo"       : ["../js_for_lyfe/"],
        "target_email"      : ["greg.super@super.com"],
        "dummy_repo"        : "../js_for_lyfe-mirror-repo/",
        "dummy_repo_data"   : "../js_for_lyfe-mirror-repo/data",
        "dummy_email"       : "greg.super@super.com",
        "dummy_name"        : "Greg super",
        "dummy_readme"      : "This public repository reflects the commits from a private repo (minus the actual code)",
        "dummy_ext"         : ".js",
        "dummy_code"        : "'use strict';",
        "hide_commits"      : true,
        "auto_push"         : true,
        "force"             : false,
        "remote"            : "https://github.com/Duder-onomy/js_for_lyfe-mirror-repo.git"
    }
]
```

Getting this error: 
```shell
since:
Log Split Length: 4
PRIVATE COMMIT MESSAGE: Commit message is private
Traceback (most recent call last):
  File "gitdummy.py", line 144, in <module>
    dummyfile = open(repo['dummy_repo_data'] + os.path.sep + commit['filename']+repo['dummy_ext'], 'w+')
IOError: [Errno 2] No such file or directory: u'../js_for_lyfe-mirror-repo/data/initial-commit-114f642.js'
```

I can confirm that both that directory and that file exist. 

Is it because my repo paths are relative?

**Comment by ebrian** [comment]
I believe that is your issue, yes. If you use absolute paths instead, does this solve your problem?

**Comment by Duder-onomy** [comment]
testing now. Thanks for the quick reply.

**Comment by ebrian** [comment]
Also, glad you like the project. :)

**Comment by Duder-onomy** [comment]
Totally worked. Thanks, 
One more question and maybe this should be a sep issue. Is it possible to get other branches? It looks like it currently only uses master?

**Comment by ebrian** [comment]
Yeah, it does. We were trying to align with how GitHub does it for public, which is to say that your contributions on branches other than master are excluded. GitDummy would still have to abide by that in that having a separate branch in your dummy repo would not show up as contributions anyway. There is also the issue of having commits from another branch in master, and then having them appear a second time once that branch gets merged.

I'm definitely open to more discussion on it though.

**Comment by Duder-onomy** [comment]
Interesting. I think you are correct. I will think about it more and git back to you. Thanks for the time.

**Comment by ebrian** [comment]
Thanks.
