### ISSUE TITLE
TypeError: Type str doesn't support the buffer API

### ISSUE THREAD

**Issue by jjobes** [ebrian/gitdummy#14]
After running 

    python gitdummy.py

I get the following error:

    since:
    Traceback (most recent call last):
        File "gitdummy.py", line 102, in <module>
        log_split = log_output.split('\n')
    TypeError: Type str doesn't support the buffer API

I'm running Python 3.4.2

**Comment by oehokie** [comment]
That is probably why... I'm running on python 2.7.X   I *think* split became partition in python 3.x

**Comment by oehokie** [comment]
Deleted my last comment as it wasn't true.

Looks like your `.gitdummy` file may be empty or have a space in it which is throwing it off.  Delete that file and try again?

**Comment by jjobes** [comment]
I just reverted to Python 2.7.9 and everything seems to be working fine now :+1:

**Comment by ebrian** [comment]
I'm going to look at making this 3+ friendly this weekend unless that's not possible, then I'll just add some feedback in case the user is running 3+.

**Comment by jjobes** [comment]
Thanks for taking a look at it, and thanks also for the great project!

**Comment by ebrian** [comment]
Glad you're enjoying it and/or finding it useful. Thanks for the support.

**Comment by ebrian** [comment]
@jjobes Works on Python 3 now.

**Comment by jjobes** [comment]
Great, thanks for the fix.
