### ISSUE TITLE
Working on windows machine

### ISSUE THREAD

**Issue by ogencoglu** [ebrian/gitdummy#22]
Hi,

Thanks for the repo. I have been trying to get this working on Windows but I get such an error:

```python
C:\Users\oguzhangencoglu\SkyDrive\Oguz\GitHub\gitdummy>python gitdummy.py
since:
Traceback (most recent call last):
  File "gitdummy.py", line 92, in <module>
    '--pretty=format:%an||||%ae||||%ad||||%s||||%f-%h'
  File "C:\Users\oguzhangencoglu\AppData\Local\Enthought\Canopy\App\appdata\canopy-1.5.5.3123.win-x86_64\lib\subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "C:\Users\oguzhangencoglu\AppData\Local\Enthought\Canopy\App\appdata\canopy-1.5.5.3123.win-x86_64\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Users\oguzhangencoglu\AppData\Local\Enthought\Canopy\App\appdata\canopy-1.5.5.3123.win-x86_64\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
```

My json file looks like this:
```python
[
    {
        "target_repo"       : ["C:\\Users\\oguzhangencoglu\\SkyDrive\\Oguz\\Universite\\Research\\Digital Health Revolution (DHR) - Health Data Mining (HDM)\\Suomi24"],
        "target_email"      : ["oguzhan.gencoglu@tut.fi"],
        "dummy_repo"        : "C:\\Users\\oguzhangencoglu\\SkyDrive\\Oguz\\GitHub\\dummy_repo",
        "dummy_repo_data"   : "C:\\Users\\oguzhangencoglu\\SkyDrive\\Oguz\\GitHub\\dummy_repo\\data",
        "dummy_email"       : "oguzhan.gencoglu@tut.fi",
        "dummy_name"        : "Oguzhan Gencoglu",
        "dummy_readme"      : "This public repository reflects the commits from a private repo (minus the actual code)",
        "dummy_ext"         : "",
        "dummy_code"        : "'use strict';",
        "hide_commits"      : true,
        "random_file_name"  : false,
        "auto_push"         : false,
        "force"             : false,
        "remote"            : "https://github.com/ogencoglu/dummy_repo"
    }
]
```

Any help would be great.

**Comment by ebrian** [comment]
This seems like a Windows path issue or something similar. Before I do anymore troubleshooting, could you try escaping the spaces in your "target_repo".

This
`"C:\\Users\\oguzhangencoglu\\SkyDrive\\Oguz\\Universite\\Research\\Digital\ Health\ Revolution\ (DHR)\ -\ Health\ Data\ Mining\ (HDM)\\Suomi24"`

in favor of

`"C:\\Users\\oguzhangencoglu\\SkyDrive\\Oguz\\Universite\\Research\\Digital Health Revolution (DHR) - Health Data Mining (HDM)\\Suomi24"`

**Comment by ogencoglu** [comment]
Thanks a lot for quick reply. I think the previous was correct. Now can't even parse json.

```python
Traceback (most recent call last):
  File "gitdummy.py", line 13, in <module>
    repos = json.load(open('repos.json'))
  File "C:\Users\oguzhangencoglu\AppData\Local\Enthought\Canopy\App\appdata\canopy-1.5.5.3123.win-x86_64\lib\json\__init__.py", line 290, in load
    **kw)
  File "C:\Users\oguzhangencoglu\AppData\Local\Enthought\Canopy\App\appdata\canopy-1.5.5.3123.win-x86_64\lib\json\__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "C:\Users\oguzhangencoglu\AppData\Local\Enthought\Canopy\App\appdata\canopy-1.5.5.3123.win-x86_64\lib\json\decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\oguzhangencoglu\AppData\Local\Enthought\Canopy\App\appdata\canopy-1.5.5.3123.win-x86_64\lib\json\decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid \escape: line 3 column 106 (char 113)
```

Line 3 column 106 corresponds to the first backslash after "Digital"

**Comment by ebrian** [comment]
I need to hunt down a Windows box. I'll have a look at this again then.

**Comment by webcaetano** [comment]
@ogencoglu  I use windows 8 , and acctually work.
Nice stuff @ebrian well done. :tada: 

Maybe in you case those space and characters mess them up
```
Digital Health Revolution (DHR) - Health Data Mining (HDM)
```

**Comment by ebrian** [comment]
@webcaetano Ha, congratulations on being the 100th :), I knew it was close and I'm proud to see how GitDummy has grown.

I wonder how I can go about fixing his issue. I simply don't own Windows machines, so, it's tough for me to troubleshoot.

**Comment by webcaetano** [comment]
I can try. But I have very sorth knowledge in python.
The error pretty sure are in escape the string

**Comment by ebrian** [comment]
I installed a Windows VM, so I'll have a look at this shortly.

**Comment by GeneOsborne** [comment]
I was also having this error. It turned out that git had not been added to the system file path, so the file not found error was being thrown because git was not registering as a valid command. This had previously not been an issue for me, because I had been using MINGW32 rather than the native windows command line.

**Comment by realtux** [comment]
@ogencoglu Issue #32 was this exact problem. It had something to do with a non-printable character slipping into the repos.json.

**Comment by ogencoglu** [comment]
Thanks, I will check. You can close the issue.
