### ISSUE TITLE
Auto Credentials

### ISSUE THREAD

**Issue by webcaetano** [ebrian/gitdummy#28]
Hi, how are you guys doing?
Is there anyway auto send credentials? 
So we don't have to input the credentials every-time.

**Comment by ebrian** [comment]
Well, you have a couple options for that. You could store the username and password within `git config` or you can write it directly in the URL: `https://username:password@github.com/username/repo`.

**Comment by webcaetano** [comment]
O____________O
Omg.
Huge thanks. Case closed.

**Comment by ebrian** [comment]
You bet :). Don't forget to star!

**Comment by webcaetano** [comment]
:tada: I'm the your 100 star
https://github.com/ebrian/gitdummy/issues/22#issuecomment-152719901

**Comment by ebrian** [comment]
Yeah, I edited my comment right after I posted it. I thought I recognized your name.
