### ISSUE TITLE
Not working on Mac

### ISSUE THREAD

**Issue by Hadjimina** [ebrian/gitdummy#32]
Heyo 
So i just found your project ( which looks awesome btw. ), however when I tried to run it on my mac I only get :

```
Traceback (most recent call last):
  File "./gitdummy.py", line 15, in <module>
    repos = json.load(open('repos.json'))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 5 column 95 (char 104)
```

Any ideas how I can make it work ?
Thx in advance

**Comment by realtux** [comment]
Most users are on Mac, so I know for sure it works on Mac. The error leads me to believe invalid JSON. Could you post your repos.json file here?

**Comment by Hadjimina** [comment]
Let me have a look at the  JSON file again and I'll come back to you. Don't want to waste your time with a stupid typo.
If I don't respond in the next 48 hours, please close the issue. 

Thanks for the fast response btw.

**Comment by Hadjimina** [comment]
wrong submit button XP

**Comment by realtux** [comment]
You bet. If it was in fact invalid JSON, I'd like to add JSON validity as a feature to this product. Let me know one way or another.

**Comment by Hadjimina** [comment]
I tried a bunch of different things and I still doesn't seem to work, even though the JSON is valid. (Same error message)

> [{
>         "target_repo": "/Users/philipphadjimina/Documents/Development/iOS/Fahrschule-Koch-mobile/",
>         "target_email": "philipp.hadjimina@gmx.ch",
>         "dummy_repo": "/Users/philipphadjimina/Documents/Development/iOS/dummy_myrepo",
>         "dummy_repo_data": "/Users/philipphadjimina/Documents/Development/iOS/data",
>         "dummy_email": "philipp.hadjimina@gmx.ch",
>         "dummy_name": "Hadjimina",
>         "dummy_readme": "This public repository reflects the commits from a private repo,namely Koch Mobile (minus the actual code)",
>         "dummy_ext": ".m",
>         "dummy_code": "NSLog (@'Hello - World!');",
>         "hide_commits": true,
>         "random_file_name": true,
>         "auto_push": true,
>         "force": false,
>         "remote": "https://github.com/Hadjimina/Koch-Mobile-dummy.git"
>     }
> 
> ]

**Comment by realtux** [comment]
So, I tried your exact repos.json and it worked fine. It did tell me that the directory doesn't exist, but that was expected. I tried it with both Python 2.7 and Python 3. This is kind of bizarre. Can you try copying the sample from the repo just in case some non-printable character got slipped in there somewhere?

On another note (not related to this problem): Change
`/Users/philipphadjimina/Documents/Development/iOS/data`
to
`/Users/philipphadjimina/Documents/Development/iOS/dummy_myrepo/data`

**Comment by Hadjimina** [comment]
So I copy & pasted it from my very comment above and it kind of worked. However I now get a completely different error :

```
since: 
fatal: Not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "./gitdummy.py", line 96, in <module>
    '--pretty=format:%an||||%ae||||%ad||||%s||||%f-%h'
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 629, in check_output
    **kwargs).stdout
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 711, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'log', '--reverse', '--pretty=format:%an||||%ae||||%ad||||%s||||%f-%h']' returned non-zero exit status 128
```

I thought maybe I had to `git init` first but there already exists a .git. Here the entire directory :

`.DS_Store   .gitignore  data        repos.json
        .git        README.md   gitdummy.py
`

Thanks a million for your help man, really appreciate it.

**Comment by DavideDaniel** [comment]
`"target_repo": "/Users/philipphadjimina/Documents/Development/iOS/Fahrschule-Koch-mobile/",
"target_email": "philipp.hadjimina@gmx.ch"`

These need to be an array, even if it is just 1 item.

**Comment by Hadjimina** [comment]
That fixed it !
Thanks guys, you were awesome !

**Comment by realtux** [comment]
@DavideDaniel Jeez, it's my own project and I missed that. Ha!
