### ISSUE TITLE
"Invalid \escape" issue - Using iCloud Directory

### ISSUE THREAD

**Issue by stefanzier** [ebrian/gitdummy#33]
Hello. First off I'd like to say that gitdummy looks great and I can't wait to get everything up and running! Nice work!

Unfortunately it seems that there's an error on line 3 of my repos.json. I store my private repository in an iCloud folder on my mac. The path is correct (I've tested in terminal multiple times) but after running the python gitdummy.py command it seems that there is an "Invalid \escape" error. 

Any suggestions? I have posted my repos.json and the terminal output below.

**repos.json**
`

  [

```
{

    "target_repo"         : ["/Users/stefanzier/Library/Mobile\ Documents/com\~apple\~CloudDocs/fitpin-info"],

    "target_email"        : ["szier@icloud.com"],
    "dummy_repo"          : "/Users/stefanzier/Desktop/public-fitpin-repo",
    "dummy_repo_data"     : "/Users/stefanzier/Desktop/public-fitpin-repo/data",
    "dummy_email"         : "szier@icloud.com",
    "dummy_name"          : "Stefan Zier",
    "dummy_readme"        : "This public repository reflects the commits from a private repo (minus the actual code)",
    "dummy_ext"           : ".js",
    "dummy_code"          : "'use strict';",
    "hide_commits"        : false,
    "random_file_name"    : true,
    "auto_push"           : true,
    "force"               : true,
    "remote"              : "https://github.com/stefanzier/public-fitpin-repo"
}
```

  ]
`

**Terminal Output:**
`Traceback (most recent call last):
  File "gitdummy.py", line 15, in <module>
    repos = json.load(open('repos.json'))
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid \escape: line 3 column 67 (char 74)`

Thank you!

**Comment by realtux** [comment]
It's gotta be either the `\[space]` or `\~`. Trying removing the backslashes and just write it as is.

**Comment by stefanzier** [comment]
Thanks for the quick reply! I replaced the `\` with `/`. I also tried removing the `~` as well but got an error that there was `No such file or directory`. 

Any other suggestions? I appreciate the help!

**Comment by realtux** [comment]
Don't replace `\` with `/`. I was thinking go from

`"/Users/stefanzier/Library/Mobile\ Documents/com\~apple\~CloudDocs/fitpin-info"`

to

`"/Users/stefanzier/Library/Mobile Documents/com~apple~CloudDocs/fitpin-info"`

**Comment by stefanzier** [comment]
Thank you!!! That worked. You're a genius.

**Comment by realtux** [comment]
Nice.

Generally `\` is only in the terminal where it's an unquoted string.

For instance,

`ls -l /Users/stefanzier/Library/Mobile Documents/com~apple~CloudDocs/fitpin-info`

would be read as

```
ls -l /Users/stefanzier/Library/Mobile
ls -l Documents/com/Users/stefanzierapple/Users/stefanzierCloudDocs/fitpin-info
```

Glad you got it sorted though :)
