### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by lansana** [ebrian/gitdummy#36]
This script doesn't work anymore. It completes successfully, however the history does not get added.

I have private repos I commit to on another Github account and want the history to transfer over, but I don't see it updated on my history. However, in my dummy repo, the commits are there. 

So again, the script works, but the history is not added any longer.

**Comment by realtux** [comment]
unfortunately github made this project obsolete by adding this functionality into their platform, so the project is no longer maintained or improved
