### ISSUE TITLE
Can't rerun the python script

### ISSUE THREAD

**Issue by omarfouad** [ebrian/gitdummy#8]
Whenever I run the python script I get the following message
...
Your branch is up-to-date with 'origin/master'.

Untracked files:
	.DS_Store
	commits/-4ffd501.js

nothing added to commit but untracked files present
fatal: remote origin already exists.
Branch master set up to track remote branch master from origin.
Everything up-to-date
since: Tue Jan 13 00:57:20 2015 +0100
Log Split Length: 1
Traceback (most recent call last):
  File "gitdummy.py", line 121, in <module>
    if len(commits) > 0:
NameError: name 'commits' is not defined
...

I had to delete to remove these files from the working directory (of the dummy repo) to make it work. Also I can't get to run the script for multiple repos at the same time. Sometimes the repos get mixed together, committing to the wrong repo.

**Comment by omarfouad** [comment]
Sorry, maybe my lats comment wasn't really clear. 

What I'm doing, is adding repos gradually to the json file. The scenario is as follows:

1. I add one repo in the json file, specifying all the data needed
2. I create the dummy, public repo on github
3. I run the script, everything works fine, on github the repo is there with all the commits from the real repo
4. I want to add a new repo to the json file, so I append that to to the existing array, like so:

```json
[
    {
        "target_repo"       : ["/Users/omarfouad/work/git/cstorepro-website"],
        "target_email"      : ["omarfouad.net@gmail.com"],
        "dummy_repo"        : "/Users/omarfouad/work/git/dummy/cstorepro-modules",
        "dummy_repo_data"   : "/Users/omarfouad/work/git/dummy/cstorepro-modules/src",
        "dummy_email"       : "omarfouad.net@gmail.com",
        "dummy_name"        : "Omar Fouad",
        "dummy_ext"         : ".js",
        "dummy_code"        : "// Code is hidden as this is a private repository",
        "hide_commits"      : false,
        "auto_push"         : true,
        "force"             : false,
        "remote"            : "https://github.com/omarfouad/cstorepro-modules-pub"
    },
    {
        "target_repo"       : ["/Users/omarfouad/work/fi/finish-app"],
        "target_email"      : ["omarfouad.net@gmail.com"],
        "dummy_repo"        : "/Users/omarfouad/work/git/dummy/finish-frontend",
        "dummy_repo_data"   : "/Users/omarfouad/work/git/dummy/finish-frontend/src",
        "dummy_email"       : "omarfouad.net@gmail.com",
        "dummy_name"        : "Omar Fouad",
        "dummy_ext"         : ".js",
        "dummy_code"        : "// Code is hidden as this is a private repository",
        "hide_commits"      : false,
        "auto_push"         : true,
        "force"             : false,
        "remote"            : "https://github.com/omarfouad/finish-frontend-pub"
    }
]
```
3. I create the new repo on github
4. I run the script. From what I seeing on terminal, the script is trying to push the first repo, but it never makes it to the second repo, thus doesn't push it:

```sh
Reinitialized existing Git repository in /Users/omarfouad/work/git/dummy/cstorepro-modules/.git/
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
fatal: remote origin already exists.
Branch master set up to track remote branch master from origin.
Everything up-to-date
since: Tue Jan 13 00:51:11 2015 +0100
Log Split Length: 1
Traceback (most recent call last):
  File "gitdummy.py", line 121, in <module>
    if len(commits) > 0:
NameError: name 'commits' is not defined
```

Am I missing something? 
Thanks.

**Comment by omarfouad** [comment]
A while ago I deleted all the dummy repos and their respective repos on github, keeping the json file untouched. I re-created the repos on github and run the python file. The repos got pushed on github as expected. After a while I made a change to one of the real repos and I pushed it. After that, wanting to update its dummy repo, I re-run the script, which pushed the new commit but on **both the dummy repos on github*. 

Ideas?

**Comment by oehokie** [comment]
I get the same "NameError: name 'commits' is not defined" message when I have no new commits to sync.  I just pushed a new version which should fix this

**Comment by omarfouad** [comment]
Thanks for the reply. It doesn't show any error now. But what happens is far more complicated. 
I actually have three dummy repos setup in the JSON file. I made a commit in one of them (in a real repo) and pushed. Then I run the python file and it worked fine, except it pushed that commit to all the three dummy repos on github. If you check my activity here: https://github.com/omarfouad?tab=activity
you'll see the same commit that belongs to the repo https://github.com/omarfouad/cstorepro-modules-pub was pushed even on https://github.com/omarfouad/finish-frontend-pub and https://github.com/omarfouad/cstorepro-ios-pub.

**Comment by omarfouad** [comment]
Here is the JSON file I have now:

```json
[
    {
        "target_repo"       : ["/Users/omarfouad/work/git/cstorepro-website"],
        "target_email"      : ["omarfouad.net@gmail.com"],
        "dummy_repo"        : "/Users/omarfouad/work/git/dummy/cstorepro-modules",
        "dummy_repo_data"   : "/Users/omarfouad/work/git/dummy/cstorepro-modules/src",
        "dummy_email"       : "omarfouad.net@gmail.com",
        "dummy_name"        : "Omar Fouad",
        "dummy_ext"         : ".js",
        "dummy_code"        : "// Code is hidden as this is a private repository",
        "hide_commits"      : false,
        "auto_push"         : true,
        "force"             : false,
        "remote"            : "https://github.com/omarfouad/cstorepro-modules-pub"
    },
    {
        "target_repo"       : ["/Users/omarfouad/work/fi/finish-app"],
        "target_email"      : ["omarfouad.net@gmail.com"],
        "dummy_repo"        : "/Users/omarfouad/work/git/dummy/finish-frontend",
        "dummy_repo_data"   : "/Users/omarfouad/work/git/dummy/finish-frontend/src",
        "dummy_email"       : "omarfouad.net@gmail.com",
        "dummy_name"        : "Omar Fouad",
        "dummy_ext"         : ".js",
        "dummy_code"        : "// Code is hidden as this is a private repository",
        "hide_commits"      : false,
        "auto_push"         : true,
        "force"             : false,
        "remote"            : "https://github.com/omarfouad/finish-frontend-pub"
    },
    {
        "target_repo"       : ["/Users/omarfouad/work/git/cstorepro-ios"],
        "target_email"      : ["omarfouad.net@gmail.com"],
        "dummy_repo"        : "/Users/omarfouad/work/git/dummy/cstorepro-ios",
        "dummy_repo_data"   : "/Users/omarfouad/work/git/dummy/cstorepro-ios/src",
        "dummy_email"       : "omarfouad.net@gmail.com",
        "dummy_name"        : "Omar Fouad",
        "dummy_ext"         : ".js",
        "dummy_code"        : "// Code is hidden as this is a private repository",
        "hide_commits"      : false,
        "auto_push"         : true,
        "force"             : false,
        "remote"            : "https://github.com/omarfouad/cstorepro-ios-pub"
    }
]

```

**Comment by oehokie** [comment]
Hmmm, yes that is a problem.  Apparently it's been doing that on mine all along and I didn't notice.  Probably an easy fix, let me take a look

**Comment by oehokie** [comment]
That should do it.  I just did a test and it seemed to go to the right repo (and not the wrong one).

Looks like I'll have to go back and clean up my stuff... fun...

**Comment by oehokie** [comment]
Actually... wasn't that bad.  Just deleted the repo and folder with the "public" repo on my harddrive, re-ran the script and it synced everything right up

**Comment by oehokie** [comment]
@omarfouad Everything good now?

**Comment by omarfouad** [comment]
Hmm, did you delete the repos on github before cleaning up? There might be dupes in commits. It happened with me once :)

Anyways I'll check and let you know.

**Comment by oehokie** [comment]
@omarfouad I'm not sure what you mean.  With the changes, here's what I did:

* I deleted my dummy repos off of github
* I deleted the dummy repos off my hard drive
* I re-created clean dummy repos on github
* I re-ran the gitdummy.py script (it creates it's own folders on the hard drive, so no need to recreate)

**Comment by omarfouad** [comment]
Yes, exactly. I thought you didn't delete the dummy repos on github. 

Good job again.

**Comment by oehokie** [comment]
Thanks.  I'm going to go ahead and close this since the original issue is resolved.  If something else pops up, let me know.
